# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notification_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 158)
        self.messageLabel = QtWidgets.QLabel(Dialog)
        self.messageLabel.setGeometry(QtCore.QRect(20, 20, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.messageLabel.setFont(font)
        self.messageLabel.setWordWrap(True)
        self.messageLabel.setObjectName("messageLabel")
        self.closeButton = QtWidgets.QPushButton(Dialog)
        self.closeButton.setGeometry(QtCore.QRect(180, 120, 93, 28))
        self.closeButton.setObjectName("closeButton")
        self.remindLaterButton = QtWidgets.QPushButton(Dialog)
        self.remindLaterButton.setGeometry(QtCore.QRect(290, 120, 93, 28))
        self.remindLaterButton.setObjectName("remindLaterButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.messageLabel.setText(_translate("Dialog", "You have been looking at screen for 2 hrs. It\'s a reminder for you to take a break and refresh yourself!! "))
        self.closeButton.setText(_translate("Dialog", "OK"))
        self.remindLaterButton.setText(_translate("Dialog", "Remind again"))
